apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vllm-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/DmitriyBratko/mlops-sandbox.git'
    targetRevision: HEAD
    path: infra/llm
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
